/* SPDX-License-Identifier: GPL-2.0-only */
/* Copyright (c) 2026 Nuvoton Technology Corporation. */

#ifndef VC_HW_REGS_H
#define VC_HW_REGS_H

/* Decoder synthesis-register feature positions. */
#define VC_HW_CFG_MPEG2_SHIFT	31U
#define VC_HW_CFG_VC1_SHIFT	29U
#define VC_HW_CFG_JPEG_SHIFT	28U
#define VC_HW_CFG_MPEG4_SHIFT	26U
#define VC_HW_CFG_H264_SHIFT	24U
#define VC_HW_CFG_VP6_SHIFT	23U
#define VC_HW_CFG_RV_SHIFT	26U
#define VC_HW_CFG_VP8_SHIFT	23U
#define VC_HW_CFG_VP7_SHIFT	24U
#define VC_HW_CFG_WEBP_SHIFT	19U
#define VC_HW_CFG_AVS_SHIFT	22U
#define VC_HW_CFG_PP_SHIFT	16U
#define VC_HW_CFG_PROGRESSIVE_JPEG_SHIFT	22U
#define VC_HW_CFG_REF_BUFFER_SHIFT	20U
#define VC_HW_CFG_SORENSON_SHIFT	11U

#define VC_HW_CFG2_JPEG_EXT_SHIFT	31U
#define VC_HW_CFG2_REF_INTERLACED_SHIFT	30U
#define VC_HW_CFG2_MPEG4_CUSTOM_SHIFT	29U
#define VC_HW_CFG2_REF_DOUBLE_SHIFT	28U
#define VC_HW_CFG2_MVC_SHIFT	20U
#define VC_HW_CFG2_TILED_SHIFT	17U
#define VC_HW_CFG2_WIDTH_EXT_SHIFT	14U
#define VC_HW_CFG2_EC_SHIFT	12U
#define VC_HW_CFG2_STRIDE_SHIFT	11U
#define VC_HW_CFG2_FIELD_DPB_SHIFT	10U
#define VC_HW_CFG2_AVS_PLUS_SHIFT	6U
#define VC_HW_CFG2_ADDR64_SHIFT	5U

#define VC_HW_FUSE_H264_SHIFT	31U
#define VC_HW_FUSE_MPEG4_SHIFT	30U
#define VC_HW_FUSE_MPEG2_SHIFT	29U
#define VC_HW_FUSE_SORENSON_SHIFT	28U
#define VC_HW_FUSE_JPEG_SHIFT	27U
#define VC_HW_FUSE_VP6_SHIFT	26U
#define VC_HW_FUSE_VC1_SHIFT	25U
#define VC_HW_FUSE_PROGRESSIVE_JPEG_SHIFT	24U
#define VC_HW_FUSE_CUSTOM_MPEG4_SHIFT	23U
#define VC_HW_FUSE_RV_SHIFT	22U
#define VC_HW_FUSE_VP7_SHIFT	21U
#define VC_HW_FUSE_VP8_SHIFT	20U
#define VC_HW_FUSE_AVS_SHIFT	19U
#define VC_HW_FUSE_MVC_SHIFT	18U
#define VC_HW_FUSE_REF_BUFFER_SHIFT	7U
#define VC_HW_PP_FUSE_ENABLE_SHIFT	31U

/* VC8000 software-register indices. */
#define VC_HW_DEC_IRQ_REG	1U
#define VC_HW_PP_IRQ_REG	60U
#define VC_HW_DEC_SYNTH_REG	50U
#define VC_HW_DEC_SYNTH2_REG	54U
#define VC_HW_PP_SYNTH_REG	100U

/* Decoder and post-processor control/status bits. */
#define VC_HW_DEC_ENABLE	0x01U
#define VC_HW_PP_ENABLE	0x01U
#define VC_HW_DEC_ABORT	0x20U
#define VC_HW_DEC_IRQ_DISABLE	0x10U
#define VC_HW_PP_IRQ_DISABLE	0x10U
#define VC_HW_DEC_IRQ_PENDING	0x100U
#define VC_HW_PP_IRQ_PENDING	0x100U

#endif /* VC_HW_REGS_H */
